# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(srctree)/../sm7435-modules/motorola/include \
		-I$(srctree)/../sm7435-modules/motorola/drivers/power/mmi_pl_chg_manager

obj-m += mmi_pl_chg_manager.o
