# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(srctree)/../sm7435-modules/motorola/drivers/power/fet_control
EXTRA_CFLAGS += -I$(srctree)/../sm7435-modules/motorola/include

obj-m += fet_control.o
