# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(srctree)/../sm7435-modules/motorola/include \
		-I$(srctree)/../sm7435-modules/motorola/drivers/power/mmi_sc8549

obj-m += mmi_sc8549.o


