# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(srctree)/../sm7435-modules/motorola/include \
		-I$(srctree)/../sm7435-modules/motorola/drivers/power/rt9467_chg_mmi

obj-m += rt9467_charger.o


