# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(srctree)/../sm7435-modules/motorola/include \
		-I$(srctree)/../sm7435-modules/motorola/drivers/power/bq2597x_mmi_iio

obj-m += bq2597x_mmi_iio.o

